#!/usr/bin/env node
/**
 * init-secrets.cjs
 *
 * Generate a fresh `.env` with random 256-bit secrets and 4 dev users
 * (owner / admin / agent / viewer) using scrypt hashing.
 *
 * Idempotent: refuses to overwrite an existing .env without --force.
 *
 * Usage:
 *   node scripts/init-secrets.cjs
 *   node scripts/init-secrets.cjs --force
 *   node scripts/init-secrets.cjs --port=4500
 */

const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const ENV_PATH = path.join(__dirname, '..', '.env');

function parseArgs(argv) {
  const out = { force: false, port: 4310 };
  for (const a of argv.slice(2)) {
    if (a === '--force' || a === '-f') out.force = true;
    else if (a.startsWith('--port=')) out.port = Number(a.slice('--port='.length));
    else if (a === '--help' || a === '-h') {
      console.log('Usage: node scripts/init-secrets.cjs [--force] [--port=4310]');
      process.exit(0);
    }
  }
  return out;
}

function randomHexKey(bytes) {
  return 'vv_' + crypto.randomBytes(bytes).toString('base64url');
}

function randomPassword(len = 16) {
  const chars = 'ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789';
  let s = '';
  for (let i = 0; i < len; i++) s += chars[crypto.randomInt(chars.length)];
  return s;
}

function scrypt(password, salt) {
  return new Promise((resolve, reject) => {
    crypto.scrypt(password, salt, 64, { N: 16384, r: 8, p: 1 }, (err, derived) => {
      if (err) reject(err);
      else resolve('$' + salt.toString('hex') + '$' + derived.toString('hex'));
    });
  });
}

async function buildUsers() {
  const usernames = ['owner', 'admin', 'agent', 'viewer'];
  const roles = ['owner', 'admin', 'agent', 'viewer'];
  const out = {};
  for (let i = 0; i < usernames.length; i++) {
    const salt = crypto.randomBytes(16);
    const hash = await scrypt(randomPassword(), salt);
    out[usernames[i]] = { role: roles[i], hash };
  }
  return out;
}

async function main() {
  const args = parseArgs(process.argv);
  if (fs.existsSync(ENV_PATH) && !args.force) {
    console.error(`.env already exists at ${ENV_PATH}`);
    console.error('Pass --force to regenerate (this DELETES existing users).');
    process.exit(1);
  }
  const users = await buildUsers();
  // Print credentials to stdout (so they're recoverable from CI logs).
  const recovery = {};
  for (const u of Object.keys(users)) {
    recovery[u] = randomPassword();
  }
  // Re-hash with the recovery passwords so we can persist them.
  for (const u of Object.keys(users)) {
    const salt = crypto.randomBytes(16);
    users[u].hash = await scrypt(recovery[u], salt);
  }
  const lines = [
    '# Generated by scripts/init-secrets.cjs — do not commit',
    `PORT=${args.port}`,
    `VALUER_HARDENED=1`,
    `VALUER_COOKIE_SECURE=0`,
    '',
    '# HMAC secrets',
    `VALUER_AGENT_SECRET=${randomHexKey(32)}`,
    `VALUER_ADMIN_SECRET=${randomHexKey(32)}`,
    `VALUER_SESSION_SECRET=${randomHexKey(32)}`,
    '',
    '# Session TTL ms (default 12h)',
    'VALUER_SESSION_TTL_MS=43200000',
    '',
    '# Vibe indexer (HyperEVM testnet 46630)',
    'VIBE_RPC_URL=https://rpc.testnet.chain.robinhood.com',
    'VIBE_CHAIN_ID=46630',
    '',
    '# Dev users (scrypt-hashed)',
    `VALUER_USERS_JSON=${JSON.stringify(users)}`,
    '',
    '# Recovery — printed to stdout once at init, NOT persisted in plain',
    `# USERS: ${Object.entries(recovery).map(([u, p]) => `${u}=${p}`).join('; ')}`,
  ];
  fs.writeFileSync(ENV_PATH, lines.join('\n') + '\n', { mode: 0o600 });
  console.log(`✅ wrote ${ENV_PATH} (mode 0600)`);
  console.log('');
  console.log('Dev user passwords (write these down, NOT in the repo):');
  console.log('');
  for (const [u, p] of Object.entries(recovery)) {
    console.log(`   ${u.padEnd(8)} ${p}`);
  }
  console.log('');
  console.log(`Start with:  PORT=${args.port} npm start`);
  console.log(`Open:        http://127.0.0.1:${args.port}/`);
}

if (require.main === module) {
  main().catch((e) => {
    console.error('init-secrets failed:', e);
    process.exit(1);
  });
}

module.exports = { randomHexKey, randomPassword };
