#!/usr/bin/env node
/**
 * transfer-secrets.cjs
 *
 * Helper to populate .env on the VPS without committing plaintext secrets
 * anywhere. Run interactively, paste your local .env, then the script:
 *
 *   1. Validates required keys (SECRET/USERS_JSON/PORT/HARDENED)
 *   2. Sets VALUER_COOKIE_SECURE=1 (we're behind HTTPS)
 *   3. Writes file with mode 0600
 *   4. Smoke-tests the server briefly with `npm run check`
 *
 * Usage:
 *   node scripts/transfer-secrets.cjs
 *
 * Or pipe from a file:
 *   node scripts/transfer-secrets.cjs < .env  (Linux/macOS only)
 *
 * NEVER commit, push, or paste the actual secret values into chat.
 */

const fs = require('node:fs');
const path = require('node:path');
const readline = require('node:readline');
const { execSync } = require('node:child_process');

const ENV_PATH = path.join(__dirname, '..', '.env');
const REQUIRED = [
  'VALUER_ADMIN_SECRET',
  'VALUER_AGENT_SECRET',
  'VALUER_SESSION_SECRET',
  'VALUER_USERS_JSON',
];

function readStdin() {
  return new Promise((resolve) => {
    let buf = '';
    process.stdin.on('data', (chunk) => (buf += chunk));
    process.stdin.on('end', () => resolve(buf));
  });
}

function parseEnvBlock(text) {
  const out = {};
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const m = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
    if (m) out[m[1]] = m[2];
  }
  return out;
}

function validate(env) {
  const missing = REQUIRED.filter((k) => !env[k]);
  const errors = [];
  if (missing.length) {
    errors.push(`Missing required key(s): ${missing.join(', ')}`);
  }
  // Validate USERS_JSON is real JSON
  if (env.VALUER_USERS_JSON) {
    try { JSON.parse(env.VALUER_USERS_JSON); }
    catch (e) { errors.push(`VALUER_USERS_JSON is not valid JSON: ${e.message}`); }
  }
  // Validate secrets are non-empty and look like base64url/key-like values
  for (const k of ['VALUER_ADMIN_SECRET', 'VALUER_AGENT_SECRET', 'VALUER_SESSION_SECRET']) {
    if (env[k] && env[k].length < 32) {
      errors.push(`${k} should be at least 32 chars (got ${env[k].length})`);
    }
  }
  return errors;
}

function patchForProduction(env) {
  // When running behind cloudflared + domain, enforce HTTPS cookies.
  if (env.PORT === undefined) env.PORT = '4310';
  env.VALUER_COOKIE_SECURE = '1';
  if (env.NODE_ENV === undefined) env.NODE_ENV = 'production';
  return env;
}

function serializeEnv(env) {
  const order = [
    'PORT',
    'NODE_ENV',
    'VALUER_HARDENED',
    'VALUER_COOKIE_SECURE',
    'VALUER_SESSION_TTL_MS',
    'VALUER_AGENT_SECRET',
    'VALUER_ADMIN_SECRET',
    'VALUER_SESSION_SECRET',
    'VIBE_RPC_URL',
    'VIBE_CHAIN_ID',
    'AUTO_SYNC_WORKER',
    'VALUER_USERS_JSON',
    'VALUER_BASE_URL',
    'VALUER_DECAY_USERNAME',
    'VALUER_DECAY_PASSWORD',
  ];
  const sortedKeys = Object.keys(env).sort((a, b) => {
    const ai = order.indexOf(a);
    const bi = order.indexOf(b);
    if (ai < 0 && bi < 0) return a.localeCompare(b);
    if (ai < 0) return 1;
    if (bi < 0) return -1;
    return ai - bi;
  });
  const out = ['# VibeValuer — generated by transfer-secrets.cjs for VPS'];
  out.push('# Generated: ' + new Date().toISOString());
  out.push('');
  for (const k of sortedKeys) {
    out.push(`${k}=${env[k]}`);
  }
  return out.join('\n') + '\n';
}

async function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');
  const skipCheck = args.includes('--skip-check');
  if (args.includes('--help') || args.includes('-h')) {
    console.log('Usage: node scripts/transfer-secrets.cjs [--dry-run] [--skip-check]');
    console.log('Pastes a .env block on stdin, writes .env at the repo root.');
    process.exit(0);
  }
  let input;
  if (process.stdin.isTTY) {
    console.log('=== VibeValuer secret transfer ===');
    console.log('');
    console.log('Paste your local .env below. End with Ctrl+D (Linux/macOS) or Ctrl+Z then Enter (Windows).');
    console.log('');
    input = await readStdin();
  } else {
    input = await readStdin();
  }
  if (!input.trim()) {
    console.error('Empty input. Exiting.');
    process.exit(1);
  }
  const parsed = parseEnvBlock(input);
  const errors = validate(parsed);
  if (errors.length) {
    console.error('Validation failed:');
    for (const e of errors) console.error(' - ' + e);
    process.exit(1);
  }
  const final_ = patchForProduction(parsed);
  const rendered = serializeEnv(final_);
  if (dryRun) {
    console.log('---DRY RUN---');
    console.log(rendered.replace(/=([^\n]+)/g, (_, v) => `=<redacted: ${v.length} chars>`));
    process.exit(0);
  }
  if (fs.existsSync(ENV_PATH)) {
    console.log(`Existing .env found at ${ENV_PATH}. Backing up to .env.bak.${Date.now()}`);
    fs.copyFileSync(ENV_PATH, ENV_PATH + `.bak.${Date.now()}`);
  }
  fs.writeFileSync(ENV_PATH, rendered, { mode: 0o600 });
  // Lock down permissions on Linux
  try { fs.chmodSync(ENV_PATH, 0o600); } catch (e) { /* Windows ignores */ }
  console.log(`✅ wrote ${ENV_PATH} (mode 0600)`);
  // Smoke-check the JS files (lightweight, no DB)
  if (!skipCheck) {
    try {
      console.log('Running npm run check (won\'t hit the live server)...');
      execSync('npm run check --silent', { stdio: 'inherit', cwd: path.join(__dirname, '..') });
      console.log('✅ JS files compile');
    } catch (e) {
      console.error('npm run check failed:', e.message);
    }
  }
  console.log('');
  console.log('Next:');
  console.log('  pm2 start server.js --name vibe-valuer');
  console.log('  pm2 save && pm2 startup');
  console.log('  curl http://127.0.0.1:4310/api/health');
}

if (require.main === module) {
  main().catch((e) => {
    console.error('transfer failed:', e);
    process.exit(1);
  });
}
